### PR TITLE
Merge v5.4.0 Updates from pm2 and Cherry-Pick Commit 8c29a7f

### PR DESCRIPTION
**Pull request by samiurprapon**
- [x] Merged latest changes from [pm2 release](https://github.com/Unitech/pm2/releases/tag/v5.4.0).
- [x] Cherry-picked this commit - `8c29a7feb6cbde3c8ef9eb072fee284686f1553f`.
- [x] Resolved merge and cherry-pick conflicts.

### CODE REVIEW

**Comment by ahmdsabbir** [comment]
> * [x]  Merged latest changes from [pm2 release](https://github.com/Unitech/pm2/releases/tag/v5.4.0).
> * [x]  Cherry-picked this commit - `8c29a7feb6cbde3c8ef9eb072fee284686f1553f`.
> * [x]  Resolved merge and cherry-pick conflicts.

Great job. I needed this.

**Comment by samiurprapon** [comment]
@Unitech

**Comment by Kyostenas** [comment]
Are there any updates on this?

**Comment by samiurprapon** [comment]
https://github.com/socketio/pm2/pull/2

**Pull request closed without merging**
